/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void appHasAGreeting() {
        // 1. preparar los datos de prueba
        // 2. ejecutar el método que se va a probar
        App classUnderTest = new App();
        String result = classUnderTest.getGreeting();
        // 3. verificar el resultado
        // assertNotNull(result, "app should have a greeting");
        // assertEquals("Hello World!", result, "greeting should be 'Hello World!'");
    }
}
